In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
mv1=pd.read_csv("movies.csv")
mv2=pd.read_csv("credits.csv")

In [4]:
movies=mv1.merge(mv2,on='title')

In [5]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies.shape

(4809, 23)

In [7]:
movies=movies[['genres','id','keywords','overview','title','cast','crew']]

In [8]:
movies.shape

(4809, 7)

In [9]:
movies.isnull().sum().sum()

np.int64(3)

In [10]:
movies.dropna(inplace=True)

In [11]:
movies.shape

(4806, 7)

In [12]:
movies.duplicated().sum()

np.int64(0)

In [13]:
movies.head(2)

,genres,id,keywords,overview,title,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [14]:
movies['genres'].iloc[0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [16]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [17]:
movies['genres']=movies['genres'].apply(convert)

In [18]:
movies.head(1)

,genres,id,keywords,overview,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [19]:
movies['keywords'].iloc[0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [20]:
ast.literal_eval('[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]')

[{'id': 1463, 'name': 'culture clash'},
 {'id': 2964, 'name': 'future'},
 {'id': 3386, 'name': 'space war'},
 {'id': 3388, 'name': 'space colony'},
 {'id': 3679, 'name': 'society'},
 {'id': 3801, 'name': 'space travel'},
 {'id': 9685, 'name': 'futuristic'},
 {'id': 9840, 'name': 'romance'},
 {'id': 9882, 'name': 'space'},
 {'id': 9951, 'name': 'alien'},
 {'id': 10148, 'name': 'tribe'},
 {'id': 10158, 'name': 'alien planet'},
 {'id': 10987, 'name': 'cgi'},
 {'id': 11399, 'name': 'marine'},
 {'id': 13065, 'name': 'soldier'},
 {'id': 14643, 'name': 'battle'},
 {'id': 14720, 'name': 'love affair'},
 {'id': 165431, 'name': 'anti war'},
 {'id': 193554, 'name': 'power relations'},
 {'id': 206690, 'name': 'mind and soul'},
 {'id': 209714, 'name': '3d'}]

In [21]:
movies['keywords']=movies['keywords'].apply(convert)

In [22]:
def convert_cast(obj):
    l=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter<3:
            l.append(i['name'])
            counter+=1
        else:
            break
    return l

In [23]:
movies['cast']=movies['cast'].apply(convert_cast)

In [24]:
def convert_crew(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            l.append(i['name'])
            break
    return l

In [25]:
movies['crew']=movies['crew'].apply(convert_crew)

In [26]:
movies.head(1)

,genres,id,keywords,overview,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [27]:
movies['overview'].iloc[0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [28]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [29]:
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x ])

In [30]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x ])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x ])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x ])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x ])

In [31]:
movies.head(1)

,genres,id,keywords,overview,title,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]

In [32]:
movies['Tag']=movies['genres']+movies['keywords']+movies['overview']+movies['cast']+movies['crew']

In [33]:
movies.head(1)

,genres,id,keywords,overview,title,cast,crew,Tag
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[Action, Adventure, Fantasy, ScienceFiction, c..."

In [34]:
new_df=movies[['id','title','Tag']]

In [35]:
new_df.head()

,id,title,Tag
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction, basedonnov..."

In [36]:
new_df['Tag']= new_df['Tag'].apply(lambda x:" ".join(x))

C:\Users\karan\AppData\Local\Temp\ipykernel_1340\3047791561.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Tag']= new_df['Tag'].apply(lambda x:" ".join(x))

In [37]:
new_df['Tag'].iloc[0]

'Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [38]:
new_df.head(2)

,id,title,Tag
0,19995,Avatar,Action Adventure Fantasy ScienceFiction cultur...
1,285,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drugabuse exoti...

In [39]:
new_df['Tag']=new_df['Tag'].apply(lambda x: x.lower())

C:\Users\karan\AppData\Local\Temp\ipykernel_1340\666054675.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Tag']=new_df['Tag'].apply(lambda x: x.lower())

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [41]:
vectors =cv.fit_transform(new_df['Tag']).toarray()

In [42]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [43]:
np.set_printoptions(threshold=5000)

In [44]:
cv.get_feature_names_out()

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '18', '18th', '18thcentury', '19', '1930s', '1940s', '1950s',
       '1960s', '1970s', '1980', '1980s', '1985', '1990s', '19th',
       '19thcentury', '20', '200', '2009', '20th', '21st', '23', '24',
       '25', '30', '300', '3d', '40', '50', '500', '60', '60s', '70',
       '70s', 'aaron', 'aaroneckhart', 'abandoned', 'abducted',
       'abigailbreslin', 'abilities', 'ability', 'able', 'aboard',
       'abuse', 'abusive', 'academy', 'accept', 'accepted', 'accepts',
       'access', 'accident', 'accidental', 'accidentally', 'accompanied',
       'accomplish', 'account', 'accountant', 'accused', 'ace', 'achieve',
       'act', 'acting', 'action', 'actionhero', 'actions', 'activist',
       'activities', 'activity', 'actor', 'actors', 'actress', 'acts',
       'actual', 'actually', 'adam', 'adams', 'adamsandler',
       'adamshankman', 'adaptation', 'adapted', 'addict', 'addicted',
       'addiction', 'adolescence', 'adopt', 'adopted', 'adoption',
       'adopts', 'adrienbrody', 'adult', 'adultanimation', 'adultery',
       'adulthood', 'adults', 'advantage', 'adventure', 'adventures',
       'advertising', 'advice', 'affair', 'affairs', 'affect',
       'affection', 'affections', 'afghanistan', 'africa', 'african',
       'africanamerican', 'aftercreditsstinger', 'afterlife', 'aftermath',
       'age', 'aged', 'agedifference', 'agency', 'agenda', 'agent',
       'agents', 'aggressive', 'aging', 'ago', 'agree', 'agrees', 'ahead',
       'aid', 'aidanquinn', 'aided', 'aids', 'ailing', 'air', 'airplane',
       'airplanecrash', 'airport', 'aka', 'al', 'alabama', 'alan',
       'alaska', 'albert', 'alcohol', 'alcoholic', 'alcoholism',
       'alecbaldwin', 'alex', 'alfredhitchcock', 'ali', 'alice', 'alien',
       'alieninvasion', 'alienlife', 'alienplanet', 'aliens', 'alike',
       'alive', 'allen', 'alliance', 'allied', 'allies', 'allow',
       'allows', 'ally', 'alongside', 'alpacino', 'alter', 'alternate',
       'alternative', 'alzheimer', 'amanda', 'amandapeet',
       'amandaseyfried', 'amateur', 'amazing', 'ambassador', 'ambition',
       'ambitious', 'ambulance', 'ambush', 'america', 'american',
       'americanabroad', 'americanfootball', 'americans', 'amid',
       'amidst', 'amnesia', 'amp', 'amsterdam', 'amusementpark', 'amy',
       'amyadams', 'amysmart', 'analyst', 'anarchiccomedy', 'ancient',
       'ancientrome', 'ancientworld', 'anderson', 'andiemacdowell',
       'andrew', 'android', 'andy', 'andygarcía', 'angel',
       'angelabassett', 'angeles', 'angelinajolie', 'angels', 'anger',
       'anglee', 'angry', 'animal', 'animalattack', 'animalhorror',
       'animals', 'animated', 'animation', 'anna', 'annafaris', 'anne',
       'annehathaway', 'annemoss', 'annettebening', 'annie',
       'anniversary', 'announces', 'annual', 'anonymity', 'answer',
       'answers', 'ant', 'antarctic', 'anthology', 'anthony',
       'anthonyanderson', 'anthonyhopkins', 'anthonymackie',
       'anthropomorphism', 'anti', 'antics', 'antihero', 'antoinefuqua',
       'antoniobanderas', 'antonyelchin', 'apart', 'apartheid',
       'apartment', 'ape', 'apes', 'apocalypse', 'apocalyptic',
       'apparent', 'apparently', 'appear', 'appears', 'apple',
       'appointed', 'apprentice', 'approach', 'approaches', 'approaching',
       'april', 'aquarium', 'arab', 'arch', 'archaeologist', 'archeology',
       'archer', 'architect', 'arctic', 'area', 'aren', 'arena',
       'argument', 'arise', 'aristocrat', 'armed', 'arms', 'army',
       'arnold', 'arnoldschwarzenegger', 'arrangedmarriage',
       'arrangement', 'arrest', 'arrested', 'arrival', 'arrive',
       'arrived', 'arrives', 'arriving', 'arrogant', 'art', 'arthur',
       'article', 'artificial', 'artificialintelligence', 'artist',
       'artistic', 'artists', 'arts', 'ashes', 'ashley', 'ashleyjudd',
       'ashtonkutcher', 'asia', 'aside', 'ask', 'asked', 'asking', 'asks',
       'aspirations', 'aspiring', 'assassin', 'assassinate',
       'assassination', 'assassins', 'assault', 'assigned', 'assignment',
       'assistant', 'assumes', 'asteroid', 'astronaut', 'astronauts',
       'asylum', 'athlete', 'atomicbomb', 'attack', 'attacked', 'attacks',
       'attempt', 'attempting', 'attempts', 'attending', 'attends',
       'attention', 'attitude', 'attorney', 'attracted', 'attraction',
       'attractive', 'audience', 'audiences', 'audition', 'august',
       'aunt', 'austin', 'australia', 'australian', 'author',
       'authorities', 'authority', 'autism', 'auto', 'avenge', 'average',
       'avoid', 'awaits', 'awakens', 'award', 'away', 'awry', 'ax',
       'babe', 'baby', 'bachelor', 'backdrop', 'background',
       'backgrounds', 'bad', 'bag', 'bahamas', 'bail', 'balance', 'ball',
       'ballet', 'baltimore', 'band', 'bandits', 'bangkok', 'banished',
       'bank', 'banker', 'bankrobber', 'bankrobbery', 'bar', 'barely',
       'bargained', 'barn', 'barney', 'barry', 'barrylevinson',
       'barrysonnenfeld', 'bars', 'base', 'baseball', 'based',
       'basedoncomicbook', 'basedongraphicnovel', 'basedonnovel',
       'basedonplay', 'basedonstagemusical', 'basedontrueevents',
       'basedontruestory', 'basedontvseries', 'basedonvideogame',
       'basedonyoungadultnovel', 'basement', 'basketball', 'batman',
       'battle', 'battlefield', 'battles', 'battling', 'bay', 'beach',
       'bear', 'bears', 'beast', 'beasts', 'beat', 'beating', 'beautiful',
       'beautifulwoman', 'beauty', 'becky', 'becominganadult', 'bed',
       'bedroom', 'bee', 'beer', 'befriends', 'began', 'begin',
       'beginning', 'begins', 'behavior', 'beings', 'belief', 'beliefs',
       'believe', 'believed', 'believes', 'believing', 'beloved', 'ben',
       'benaffleck', 'beneath', 'benfoster', 'beniciodeltoro', 'benjamin',
       'benjaminbratt', 'benkingsley', 'bennett', 'benstiller', 'bent',
       'berlin', 'best', 'bestfriend', 'bet', 'beth', 'betrayal',
       'betrayed', 'bettemidler', 'better', 'betty', 'beverly', 'bible',
       'big', 'bigger', 'biggest', 'biker', 'bikini', 'billhader',
       'billionaire', 'billmurray', 'billnighy', 'billpaxton',
       'billpullman', 'billy', 'billybobthornton', 'billycrudup',
       'billycrystal', 'biography', 'bird', 'birth', 'birthday',
       'bisexual', 'bishop', 'bit', 'bite', 'bitter', 'bizarre', 'black',
       'blackmagic', 'blackmail', 'blackpeople', 'blade', 'blame',
       'blind', 'bliss', 'block', 'blonde', 'blood', 'bloodsplatter',
       'bloodthirsty', 'bloody', 'blow', 'blue', 'board', 'boarding',
       'boardingschool', 'boat', 'bob', 'bobby', 'bobbyfarrelly',
       'bobhoskins', 'bodies', 'body', 'bodyguard', 'bold', 'bollywood',
       'bomb', 'bombing', 'bond', 'bonds', 'bone', 'book', 'books',
       'border', 'bored', 'boredom', 'boring', 'born', 'boss', 'boston',
       'botched', 'bound', 'boundaries', 'bounty', 'bountyhunter',
       'bourne', 'box', 'boxer', 'boxing', 'boy', 'boyfriend', 'boys',
       'bradleycooper', 'bradpitt', 'brain', 'brand', 'brave', 'bravery',
       'brazil', 'brazilian', 'break', 'breakdown', 'breaking', 'breaks',
       'brendanfraser', 'brendangleeson', 'brent', 'brettratner', 'brian',
       'briandepalma', 'bride', 'bridge', 'brief', 'brien', 'bright',
       'brilliant', 'bring', 'bringing', 'brings', 'brink', 'britain',
       'british', 'britishsecretservice', 'brittanymurphy', 'broadway',
       'broke', 'broken', 'broker', 'brooklyn', 'brooks', 'brothel',
       'brother', 'brotherbrotherrelationship', 'brothers',
       'brothersisterrelationship', 'brought', 'brown', 'bruce',
       'brucewillis', 'brutal', 'brutality', 'brutally', 'bryansinger',
       'buck', 'buddies', 'buddy', 'buddycomedy', 'budget', 'build',
       'building', 'built', 'bully', 'bullying', 'bumbling', 'bunny',
       'burglar', 'buried', 'bus', 'bush', 'business', 'businessman',
       'bust', 'busy', 'butcher', 'butler', 'butt', 'buy', 'buzz',
       'cabin', 'caesar', 'cage', 'cairo', 'cal', 'california', 'called',
       'calling', 'calls', 'calvin', 'camcorder', 'came', 'camera',
       'cameraman', 'cameras', 'camerondiaz', 'camp', 'campaign',
       'campbell', 'camping', 'campus', 'canada', 'canadian', 'cancer',
       'candidate', 'candy', 'canine', 'cannibal', 'canuxploitation',
       'capable', 'caper', 'capital', 'capitalism', 'capt', 'captain',
       'captive', 'capture', 'captured', 'captures', 'car', 'caraccident',
       'carchase', 'carcrash', 'card', 'care', 'career', 'carefree',
       'cares', 'caretaker', 'careymulligan', 'caribbean', 'carjourney',
       'carl', 'carlagugino', 'carmen', 'carol', 'carolina', 'carrace',
       'carrie', 'carry', 'carrying', 'cars', 'cartel', 'carter',
       'cartoon', 'caryelwes', 'case', 'caseyaffleck', 'cash', 'casino',
       'cast', 'castle', 'cat', 'cataclysm', 'catastrophe', 'catch',
       'catches', 'cateblanchett', 'catherinekeener', 'catherinezeta',
       'catholic', 'catholicism', 'cattle', 'caught', 'cause', 'caused',
       'causes', 'causing', 'cavalry', 'cave', 'celebrate', 'celebrated',
       'celebration', 'celebrity', 'cellphone', 'cemetery', 'center',
       'centered', 'centers', 'central', 'centuries', 'century',
       'ceremony', 'certain', 'chain', 'chainsaw', 'challenge',
       'challenged', 'challenges', 'champion', 'championship', 'chance',
       'change', 'changed', 'changes', 'changing', 'channingtatum',
       'chaos', 'chaotic', 'chapter', 'character', 'characters', 'charge',
       'charged', 'charismatic', 'charles', 'charlie', 'charliesheen',
       'charlizetheron', 'charlotte', 'charm', 'charming', 'chase',
       'chased', 'chauffeur', 'cheating', 'cheerleader', 'chef',
       'chemical', 'cher', 'chicago', 'chicken', 'chief', 'child',
       'childabuse', 'childhero', 'childhood', 'children', 'chilling',
       'china', 'chinese', 'chip', 'chiwetelejiofor', 'chloe',
       'chloëgracemoretz', 'chloësevigny', 'chocolate', 'choice',
       'choices', 'choose', 'chosen', 'chowyun', 'chris', 'chriscolumbus',
       'chriscooper', 'chrisevans', 'chrishemsworth', 'chrisklein',
       'chrispine', 'chrisrock', 'christ', 'christian', 'christianbale',
       'christianity', 'christianslater', 'christinaapplegate',
       'christinaricci', 'christine', 'christmas', 'christmasparty',
       'christopher', 'christopherlloyd', 'christophernolan',
       'christopherplummer', 'christopherwalken', 'christophwaltz',
       'chronicle', 'chronicles', 'chuck', 'church', 'cia',
       'cigarettesmoking', 'cillianmurphy', 'cinema', 'circle', 'circuit',
       'circumstances', 'circus', 'cities', 'citizens', 'city', 'civil',
       'civilization', 'civilwar', 'claim', 'claims', 'claire',
       'clairedanes', 'clan', 'clark', 'clash', 'class', 'classes',
       'classic', 'classmate', 'classmates', 'classroom',
       'claudevandamme', 'clay', 'clean', 'clear', 'clerk', 'client',
       'clients', 'climate', 'climbing', 'clinteastwood', 'clique',
       'cliveowen', 'clock', 'clone', 'cloning', 'close', 'closed',
       'closer', 'club', 'clubs', 'clues', 'clutches', 'coach', 'coast',
       'cocaine', 'code', 'cody', 'coffin', 'cohen', 'col', 'cold',
       'coldwar', 'cole', 'colin', 'colinfarrell', 'colinfirth',
       'collapse', 'colleague', 'colleagues', 'collect', 'collection',
       'collector', 'college', 'collide', 'collins', 'collision',
       'colonel', 'colony', 'color', 'colorado', 'colorful', 'coma',
       'combat', 'combined', 'come', 'comeback', 'comedian', 'comedic',
       'comedy', 'comes', 'comet', 'comfort', 'comic', 'comics', 'coming',
       'comingofage', 'comingout', 'command', 'commander', 'commercial',
       'commit', 'commitment', 'committed', 'common', 'communication',
       'community', 'companion', 'company', 'compete', 'competing',
       'competition', 'complete', 'completely', 'complex', 'complicated',
       'complications', 'composer', 'computer', 'computervirus', 'conan',
       'concert', 'conclusion', 'condition', 'conditions', 'confederate',
       'confession', 'confidence', 'confident', 'conflict', 'confront',
       'confronted', 'confronts', 'confused', 'congress', 'conman',
       'connected', 'connecticut', 'connection', 'connections',
       'connects', 'connell', 'connie', 'connor', 'conquer', 'conscience',
       'consequences', 'conservative', 'considered', 'conspiracy',
       'conspire', 'constant', 'constantly', 'construction', 'consumed',
       'contact', 'contain', 'contemporary', 'contend', 'contest',
       'continue', 'continues', 'continuing', 'contract', 'control',
       'controlled', 'controlling', 'controversial', 'convention',
       'converge', 'convict', 'convicted', 'convince', 'convinced',
       'convinces', 'cook', 'cooking', 'cool', 'cooper', 'cop', 'cope',
       'cops', 'core', 'corner', 'corners', 'corporate', 'corporation',
       'corpse', 'corrupt', 'corruption', 'cost', 'costume', 'couldn',
       'count', 'country', 'countrymusic', 'countryside', 'county',
       'coup', 'couple', 'couples', 'courage', 'courageous', 'course',
       'court', 'courtcase', 'courteneycox', 'courtroom', 'cousin',
       'cover', 'covert', 'cow', 'cowardliness', 'cowboy', 'crab',
       'crack', 'craig', 'crash', 'crashes', 'crazy', 'create', 'created',
       'creates', 'creation', 'creator', 'creature', 'creatures',
       'credit', 'creepy', 'crew', 'crime', 'crimefighter', 'crimes',
       'criminal', 'criminals', 'crisis', 'critical', 'crocodile',
       'crook', 'crooked', 'cross', 'crossdressing', 'crossed', 'crosses',
       'crown', 'crucifixion', 'cruel', 'cruelty', 'cruise', 'crush',
       'crystal', 'cuba', 'cubagoodingjr', 'cult', 'cultfilm', 'cultural',
       'culture', 'cultureclash', 'cunning', 'cup', 'cure', 'curious',
       'current', 'curse', 'cursed', 'custody', 'customers', 'cut',
       'cyberpunk', 'cyborg', 'dad', 'daily', 'dakotafanning', 'damage',
       'dan', 'danaykroyd', 'dance', 'dancer', 'dancing', 'danger',
       'dangerous', 'dangers', 'daniel', 'danielcraig', 'danielday',
       'danielradcliffe', 'danny', 'dannyboyle', 'dannydevito',
       'dannyglover', 'dare', 'daring', 'dark', 'darkcomedy', 'darkest',
       'darkness', 'date', 'dates', 'dating', 'daughter', 'daughters',
       'dave', 'david', 'davidarquette', 'davidduchovny', 'davidfincher',
       'davidgordongreen', 'davidmorse', 'davido', 'davis', 'daxshepard',
       'day', 'days', 'dc', 'dccomics', 'dea', 'dead', 'deadly', 'deaf',
       'deal', 'dealer', 'dealers', 'dealing', 'deals', 'dean', 'death',
       'deathofafriend', 'deathpenalty', 'deaths', 'debt', 'debut',
       'decade', 'decades', 'decapitation', 'deceased', 'deceit',
       'deception', 'decide', 'decided', 'decides', 'decision',
       'decisions', 'dedicated', 'deeds', 'deep', 'deeper', 'deeply',
       'defeat', 'defend', 'defense', 'deliver', 'delivers', 'delusion',
       'demanding', 'demands', 'demimoore', 'demon', 'demonic',
       'demonicpossession', 'demons', 'dennisdugan', 'dennishopper',
       'dennisquaid', 'dentist', 'denzelwashington', 'department',
       'depressed', 'depression', 'deputy', 'deranged', 'derek',
       'descend', 'desert', 'deserted', 'designed', 'desire', 'desires',
       'desolate', 'despair', 'desperate', 'desperately', 'desperation',
       'despite', 'destined', 'destiny', 'destroy', 'destroyed',
       'destroying', 'destruction', 'details', 'detective', 'detectives',
       'determination', 'determine', 'determined', 'detroit',
       'devastating', 'develop', 'developed', 'develops', 'device',
       'devil', 'devoted', 'diabolical', 'dialogue', 'diamond', 'diane',
       'dianekeaton', 'dianekruger', 'dianelane', 'diary', 'dick',
       'dictator', 'did', 'didn', 'die', 'died', 'diego', 'dies',
       'differences', 'different', 'difficult', 'digging', 'dignity',
       'diner', 'dinner', 'dinosaur', 'dinosaurs', 'dire', 'directed',
       'direction', 'director', 'dirt', 'dirty', 'dirtycop', 'disabled',
       'disappear', 'disappearance', 'disappeared', 'disappears',
       'disaster', 'disastrous', 'discover', 'discovered', 'discovering',
       'discovers', 'discovery', 'disease', 'disfigurement', 'disgraced',
       'disguise', 'dishonesty', 'disillusioned', 'disney', 'disorder',
       'dispatched', 'distant', 'district', 'distrust', 'disturbed',
       'disturbing', 'diva', 'divided', 'division', 'divorce', 'divorced',
       'dj', 'dna', 'doc', 'doctor', 'document', 'documentary',
       'documents', 'does', 'doesn', 'dog', 'dogs', 'doing', 'doll',
       'dollar', 'dollars', 'dolphin', 'dolphlundgren', 'domination',
       'don', 'donaldpetrie', 'donaldsutherland', 'doncheadle', 'donnell',
       'doomed', 'doomsday', 'door', 'doorstep', 'doppelganger',
       'dorothy', 'double', 'doublelife', 'doubt', 'doubts', 'doug',
       'douglas', 'dougliman', 'dr', 'dracula', 'drag', 'dragon', 'drama',
       'dramatic', 'draw', 'drawing', 'drawn', 'draws', 'dream', 'dreams',
       'drew', 'drewbarrymore', 'drifter', 'drink', 'drinking', 'drive',
       'driven', 'driver', 'drives', 'driving', 'drop', 'drowning',
       'drug', 'drugabuse', 'drugaddiction', 'drugdealer', 'druglord',
       'drugs', 'drugtraffic', 'drunk', 'drunken', 'du', 'dualidentity',
       'dude', 'duel', 'duke', 'dumped', 'duo', 'duringcreditsstinger',
       'dustinhoffman', 'dutch', 'duty', 'dwarves', 'dwaynejohnson',
       'dying', 'dyinganddeath', 'dylan', 'dynamic', 'dynasty',
       'dysfunctional', 'dysfunctionalfamily', 'dystopia',
       'dystopicfuture', 'eager', 'earlier', 'early', 'earn', 'earth',
       'earthquake', 'east', 'easy', 'eating', 'eccentric', 'economic',
       'economy', 'eddie', 'eddiegriffin', 'eddiemurphy', 'edge',
       'edharris', 'editor', 'education', 'edward', 'edwardburns',
       'edwardnorton', 'effort', 'efforts', 'egg', 'ego', 'egypt',
       'egyptian', 'el', 'elaborate', 'elderly', 'election', 'elements',
       'eliaskoteas', 'elijahwood', 'eliminate', 'elisabethshue', 'elite',
       'elizabeth', 'elizabethbanks', 'ella', 'ellenburstyn', 'ellenpage',
       'ellie', 'elliot', 'ellis', 'elusive', 'elves', 'elvis', 'embark',
       'embarking', 'embarks', 'embassy', 'embroiled', 'emerge',
       'emergency', 'emerges', 'emilehirsch', 'emily', 'emilyblunt',
       'emilymortimer', 'emilywatson', 'emma', 'emmastone',
       'emmathompson', 'emmawatson', 'emotional', 'emotionally',
       'emotions', 'emperor', 'empire', 'employee', 'employees',
       'employer', 'employs', 'encounter', 'encounters', 'end', 'ended',
       'ending', 'endless', 'endoftheworld', 'ends', 'enemies', 'enemy',
       'energy', 'enforcement', 'engaged', 'engagement', 'engineer',
       'england', 'english', 'enigmatic', 'enjoy', 'enlist', 'enlists',
       'enormous', 'ensemblecast', 'ensues', 'entangled', 'enter',
       'enterprise', 'enters', 'entertainer', 'entertaining', 'entire',
       'entirely', 'entity', 'environment', 'environmental', 'epic',
       'epidemic', 'era', 'eric', 'ericbana', 'erin', 'ernest',
       'eroticism', 'erupts', 'escapade', 'escape', 'escaped',
       'escapefromprison', 'escapes', 'escaping', 'escort', 'especially',
       'espionage', 'establishment', 'estate', 'estranged', 'eternal',
       'ethan', 'ethanhawke', 'eugenelevy', 'europe', 'european', 'eva',
       'evacuation', 'evade', 'evamendes', 'evanrachelwood', 'eve',
       'evening', 'event', 'events', 'eventually', 'everybody',
       'everyday', 'evidence', 'evil', 'evolution', 'ewanmcgregor', 'ex',
       'exact', 'exactly', 'examines', 'exchange', 'exciting',
       'exclusive', 'execution', 'executive', 'exercise', 'exist',
       'existed', 'existence', 'existentialism', 'exists', 'exorcism',
       'exotic', 'exoticisland', 'expectations', 'expected', 'expects',
       'expedition', 'experience', 'experienced', 'experiences',

In [45]:
import nltk

In [46]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [47]:
def stem(text):
    s=[]
    for i in text.split():
        s.append(ps.stem(i))
    return " ".join(s)

In [48]:
new_df['Tag']=  new_df['Tag'].apply(stem)

C:\Users\karan\AppData\Local\Temp\ipykernel_1340\2564233792.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Tag']=  new_df['Tag'].apply(stem)

In [49]:
new_df.head(1)

      id   title                                                Tag
0  19995  Avatar  action adventur fantasi sciencefict culturecla...

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

In [51]:
similarity = cosine_similarity(vectors)

In [52]:
similarity

array([[1.        , 0.08740748, 0.05827165, ..., 0.02418254, 0.02564946,
        0.        ],
       [0.08740748, 1.        , 0.06451613, ..., 0.02677398, 0.        ,
        0.        ],
       [0.05827165, 0.06451613, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02418254, 0.02677398, 0.02677398, ..., 1.        , 0.07071068,
        0.04836508],
       [0.02564946, 0.        , 0.        , ..., 0.07071068, 1.        ,
        0.05129892],
       [0.        , 0.        , 0.        , ..., 0.04836508, 0.05129892,
        1.        ]], shape=(4806, 4806))

In [53]:
similarity[1]

array([0.08740748, 1.        , 0.06451613, 0.02116669, 0.08414891,
       0.12574886, 0.02146694, 0.13386989, 0.06788442, 0.08122955,
       0.09379581, 0.05751973, 0.41478068, 0.07620008, 0.12143535,
       0.08216866, 0.08740748, 0.27371875, 0.04757861, 0.11404948,
       0.08240856, 0.06558258, 0.07332356, 0.10369517, 0.14763465,
       0.12280754, 0.12143535, 0.07544932, 0.06670373, 0.05029955,
       0.12961896, 0.10369517, 0.0968719 , 0.11235088, 0.03666178,
       0.10998534, 0.08414891, 0.05905386, 0.11138648, 0.06253054,
       0.05986843, 0.07777138, 0.        , 0.05184758, 0.04233338,
       0.07265392, 0.12506108, 0.09198441, 0.09600307, 0.03335187,
       0.09677419, 0.0459922 , 0.08740748, 0.05415304, 0.03666178,
       0.08134518, 0.07658396, 0.09240617, 0.07544932, 0.10657614,
       0.        , 0.15677236, 0.13068205, 0.04888237, 0.03335187,
       0.0222773 , 0.13240679, 0.06350006, 0.10776318, 0.05499267,
       0.05751973, 0.11654331, 0.09837388, 0.04016097, 0.02648136,
       0.19354839, 0.0554274 , 0.04725728, 0.0547791 , 0.11219854,
       0.03666178, 0.08295614, 0.02952693, 0.07859438, 0.11053942,
       0.11296651, 0.06350006, 0.03126527, 0.09677419, 0.03265551,
       0.10369517, 0.10182663, 0.07544932, 0.05415304, 0.14089399,
       0.02648136, 0.0952501 , 0.08032193, 0.15179419, 0.06253054,
       0.03919309, 0.06253054, 0.04757861, 0.09433333, 0.15875016,
       0.11487594, 0.11894652, 0.07332356, 0.0513158 , 0.1693335 ,
       0.02648136, 0.06451613, 0.06670373, 0.05679618, 0.0554274 ,
       0.11654331, 0.03035884, 0.09837388, 0.01872515, 0.05239625,
       0.        , 0.09677419, 0.14089399, 0.05239625, 0.07265392,
       0.03394221, 0.12320822, 0.10369517, 0.03335187, 0.16829781,
       0.03394221, 0.08858079, 0.07544932, 0.06788442, 0.07184212,
       0.        , 0.08122955, 0.01833089, 0.14763465, 0.09198441,
       0.02707652, 0.04016097, 0.10369517, 0.12220593, 0.05905386,
       0.04800154, 0.01842712, 0.06670373, 0.07490059, 0.06842969,
       0.08910918, 0.08466675, 0.06788442, 0.04561979, 0.0352235 ,
       0.        , 0.04757861, 0.07490059, 0.08122955, 0.07184212,
       0.06180642, 0.03745029, 0.07658396, 0.02804964, 0.1000556 ,
       0.02677398, 0.06350006, 0.10998534, 0.11219854, 0.1016001 ,
       0.04888237, 0.12700013, 0.08032193, 0.02648136, 0.05905386,
       0.0547791 , 0.06558258, 0.        , 0.0554274 , 0.04120428,
       0.02467069, 0.04981355, 0.0862796 , 0.05950226, 0.0554274 ,
       0.02952693, 0.04356068, 0.20953952, 0.02421797, 0.04356068,
       0.15475519, 0.1108548 , 0.02648136, 0.11691309, 0.        ,
       0.06913011, 0.06253054, 0.07859438, 0.06350006, 0.25149773,
       0.04233338, 0.        , 0.03666178, 0.06253054, 0.02804964,
       0.08712137, 0.10059909, 0.06071767, 0.13470398, 0.08032193,
       0.0554274 , 0.02913583, 0.05296271, 0.04637389, 0.06253054,
       0.1047925 , 0.20739034, 0.07332356, 0.04637389, 0.070447  ,
       0.1000556 , 0.02619813, 0.0968719 , 0.05905386, 0.02245066,
       0.05609927, 0.06350006, 0.06558258, 0.08122955, 0.04204242,
       0.04800154, 0.        , 0.12700013, 0.07838618, 0.0968719 ,
       0.06451613, 0.03456506, 0.07490059, 0.06632365, 0.02358333,
       0.08122955, 0.08980265, 0.1000556 , 0.07944407, 0.03335187,
       0.06451613, 0.07014786, 0.03666178, 0.04981355, 0.07658396,
       0.03829198, 0.        , 0.04843595, 0.04843595, 0.05905386,
       0.02993422, 0.04356068, 0.06160411, 0.02490677, 0.06788442,
       0.1000556 , 0.02707652, 0.1026316 , 0.11235088, 0.        ,
       0.03126527, 0.02952693, 0.11757927, 0.02913583, 0.        ,
       0.08122955, 0.11219854, 0.        , 0.07859438, 0.03440614,
       0.03279129, 0.14664712, 0.04716666, 0.05354796, 0.02707652,
       0.06253054, 0.02592379, 0.03175003, 0.03080206, 0.02162194,
       0.04843595, 0.0720023 , 0.02875987, 0.        , 0.05354796,
       0.070447  , 0.05986843, 0.10776318, 0.03394221, 0.0952501 ,
       0.05827165, 0.04421577, 0.02619813, 0.        , 0.04388456,
       0.05679618, 0.02146694, 0.06350006, 0.03126527, 0.07658396,
       0.06842969, 0.03279129, 0.03704974, 0.03745029, 0.070447  ,
       0.17134312, 0.0277137 , 0.08980265, 0.        , 0.        ,
       0.09677419, 0.02358333, 0.        , 0.        , 0.03745029,
       0.03745029, 0.        , 0.08980265, 0.03456506, 0.02804964,
       0.11757927, 0.03175003, 0.06253054, 0.03279129, 0.11810772,
       0.11654331, 0.05354796, 0.09107651, 0.03225806, 0.11359237,
       0.02952693, 0.07838618, 0.0256579 , 0.        , 0.06071767,
       0.16829781, 0.06558258, 0.10301071, 0.        , 0.03335187,
       0.04981355, 0.        , 0.        , 0.070447  , 0.16395646,
       0.05751973, 0.        , 0.06350006, 0.02540003, 0.        ,
       0.06350006, 0.06558258, 0.        , 0.03456506, 0.10998534,
       0.        , 0.05986843, 0.03456506, 0.04888237, 0.0554274 ,
       0.        , 0.03175003, 0.        , 0.07184212, 0.09240617,
       0.05986843, 0.0547791 , 0.02839809, 0.        , 0.07014786,
       0.0228099 , 0.05184758, 0.        , 0.03394221, 0.05679618,
       0.        , 0.09600307, 0.        , 0.0547791 , 0.06913011,
       0.03335187, 0.07472032, 0.02913583, 0.02839809, 0.14368424,
       0.03035884, 0.04356068, 0.1000556 , 0.03035884, 0.0277137 ,
       0.        , 0.02490677, 0.02952693, 0.05354796, 0.02738955,
       0.07332356, 0.        , 0.06670373, 0.14149999, 0.        ,
       0.03279129, 0.        , 0.05609927, 0.03919309, 0.03666178,
       0.05415304, 0.09379581, 0.13694776, 0.05986843, 0.0352235 ,
       0.01903812, 0.05905386, 0.03666178, 0.03919309, 0.08032193,
       0.10955821, 0.        , 0.03919309, 0.0554274 , 0.04263046,
       0.05029955, 0.06582684, 0.03126527, 0.04233338, 0.        ,
       0.        , 0.0554274 , 0.05354796, 0.0352235 , 0.02993422,
       0.08466675, 0.        , 0.06253054, 0.        , 0.        ,
       0.        , 0.        , 0.02592379, 0.06253054, 0.02738955,
       0.        , 0.02738955, 0.02540003, 0.0547791 , 0.03126527,
       0.        , 0.0277137 , 0.03394221, 0.02839809, 0.02648136,
       0.02738955, 0.02490677, 0.09379581, 0.02514977, 0.03829198,
       0.        , 0.11757927, 0.02116669, 0.        , 0.        ,
       0.        , 0.07490059, 0.07265392, 0.06451613, 0.05029955,
       0.05239625, 0.11810772, 0.11973687, 0.0547791 , 0.        ,
       0.07265392, 0.03829198, 0.        , 0.04263046, 0.04067259,
       0.05609927, 0.        , 0.        , 0.10369517, 0.03666178,
       0.06071767, 0.10369517, 0.07490059, 0.04041435, 0.04233338,
       0.08032193, 0.04676524, 0.06558258, 0.04147807, 0.        ,
       0.07658396, 0.        , 0.        , 0.07490059, 0.03225806,
       0.03035884, 0.07014786, 0.02707652, 0.08858079, 0.03592106,
       0.07838618, 0.        , 0.07332356, 0.12320822, 0.0831411 ,
       0.02804964, 0.10182663, 0.03225806, 0.06253054, 0.09240617,
       0.        , 0.        , 0.02338262, 0.05905386, 0.        ,
       0.        , 0.        , 0.        , 0.0554274 , 0.03456506,
       0.02648136, 0.        , 0.        , 0.0256579 , 0.0277137 ,
       0.07184212, 0.05354796, 0.        , 0.03745029, 0.04490133,
       0.05827165, 0.02707652, 0.07490059, 0.        , 0.06160411,
       0.05986843, 0.04888237, 0.04293388, 0.1108548 , 0.09677419,
       0.03035884, 0.070447  , 0.09379581, 0.        , 0.08032193,
       0.        , 0.04757861, 0.        , 0.03456506, 0.03279129,
       0.01761175, 0.03080206, 0.03126527, 0.        , 0.03456506,
       0.04934137, 0.03919309, 0.        , 0.05827165, 0.0352235 ,
       0.04888237, 0.07859438, 0.        , 0.06160411, 0.10369517,
       0.04016097, 0.02318694, 0.09198441, 0.02400077, 0.0256579 ,
       0.03035884, 0.06071767, 0.06558258, 0.0513158 , 0.03279129,
       0.02677398, 0.10369517, 0.0513158 , 0.1385685 , 0.05415304,
       0.        , 0.04843595, 0.1108548 , 0.        , 0.05239625,
       0.03745029, 0.0547791 , 0.05751973, 0.        , 0.05827165,
       0.05827165, 0.1026316 , 0.06160411, 0.        , 0.0178714 ,
       0.0513158 , 0.03919309, 0.04800154, 0.06071767, 0.07490059,
       0.        , 0.        , 0.09515721, 0.        , 0.05080005,
       0.06394568, 0.02648136, 0.07544932, 0.04120428, 0.03175003,
       0.0352235 , 0.03919309, 0.02913583, 0.1047925 , 0.06071767,
       0.        , 0.03745029, 0.0237893 , 0.04843595, 0.08466675,
       0.        , 0.03225806, 0.12361285, 0.05609927, 0.02677398,
       0.02738955, 0.02875987, 0.        , 0.05080005, 0.06160411,
       0.02677398, 0.03035884, 0.        , 0.        , 0.03175003,
       0.05415304, 0.        , 0.03335187, 0.08519428, 0.06160411,
       0.1026316 , 0.06071767, 0.        , 0.        , 0.12700013,
       0.        , 0.02839809, 0.        , 0.04356068, 0.07136791,
       0.0277137 , 0.        , 0.05914273, 0.05679618, 0.05751973,
       0.07332356, 0.06788442, 0.        , 0.        , 0.10369517,
       0.08122955, 0.0554274 , 0.        , 0.07490059, 0.        ,
       0.        , 0.02875987, 0.03126527, 0.        , 0.02738955,
       0.0547791 , 0.070447  , 0.02952693, 0.06558258, 0.        ,
       0.02993422, 0.        , 0.        , 0.05354796, 0.        ,
       0.04016097, 0.03666178, 0.06253054, 0.        , 0.05679618,
       0.03126527, 0.10776318, 0.        , 0.        , 0.0720023 ,
       0.07332356, 0.0459922 , 0.08980265, 0.05029955, 0.        ,
       0.03279129, 0.        , 0.0513158 , 0.        , 0.02619813,
       0.02707652, 0.0277137 , 0.03829198, 0.02707652, 0.04716666,
       0.04757861, 0.10567049, 0.02707652, 0.        , 0.        ,
       0.11235088, 0.07490059, 0.05029955, 0.02467069, 0.04233338,
       0.        , 0.0352235 , 0.02514977, 0.        , 0.0547791 ,
       0.        , 0.        , 0.03873468, 0.05354796, 0.        ,
       0.0818717 , 0.08740748, 0.05679618, 0.        , 0.07944407,
       0.02619813, 0.0352235 , 0.05679618, 0.07838618, 0.04120428,
       0.05609927, 0.06253054, 0.03592106, 0.02738955, 0.07184212,
       0.1000556 , 0.09240617, 0.05080005, 0.04120428, 0.        ,
       0.05415304, 0.        , 0.02993422, 0.03126527, 0.05751973,
       0.08910918, 0.        , 0.        , 0.0547791 , 0.02707652,
       0.        , 0.03175003, 0.03456506, 0.        , 0.06670373,
       0.02875987, 0.        , 0.05354796, 0.04676524, 0.070447  ,
       0.05239625, 0.        , 0.03592106, 0.11757927, 0.04800154,
       0.06558258, 0.04490133, 0.07332356, 0.1385685 , 0.        ,
       0.04490133, 0.14664712, 0.05354796, 0.07490059, 0.1385685 ,
       0.06350006, 0.09677419, 0.03080206, 0.1108548 , 0.        ,
       0.02540003, 0.07184212, 0.09379581, 0.        , 0.06670373,
       0.        , 0.08240856, 0.        , 0.        , 0.03991229,
       0.08466675, 0.        , 0.        , 0.05415304, 0.05609927,
       0.06350006, 0.        , 0.02875987, 0.08712137, 0.02444119,
       0.03080206, 0.        , 0.07332356, 0.10830607, 0.03175003,
       0.02490677, 0.02400077, 0.        , 0.17282528, 0.02514977,
       0.05679618, 0.03942849, 0.02400077, 0.06670373, 0.        ,
       0.        , 0.03829198, 0.10709591, 0.02993422, 0.        ,
       0.06451613, 0.05354796, 0.02952693, 0.05354796, 0.05354796,
       0.05827165, 0.0720023 , 0.        , 0.04490133, 0.04233338,
       0.06670373, 0.05609927, 0.02592379, 0.03279129, 0.03279129,
       0.02178034, 0.        , 0.        , 0.19050019, 0.02875987,
       0.08712137, 0.        , 0.        , 0.03394221, 0.03035884,
       0.02952693, 0.0277137 , 0.        , 0.08466675, 0.0952501 ,
       0.01872515, 0.        , 0.        , 0.0352235 , 0.04934137,
       0.        , 0.08980265, 0.        , 0.05296271, 0.06670373,
       0.08216866, 0.        , 0.        , 0.04888237, 0.02913583,
       0.        , 0.        , 0.03666178, 0.03745029, 0.        ,
       0.0352235 , 0.        , 0.03175003, 0.        , 0.02952693,
       0.        , 0.        , 0.02008048, 0.05296271, 0.01925571,
       0.03035884, 0.04800154, 0.08712137, 0.02146694, 0.06451613,
       0.03175003, 0.        , 0.        , 0.05609927, 0.06253054,
       0.        , 0.03279129, 0.        , 0.07332356, 0.02490677,
       0.        , 0.04356068, 0.        , 0.        , 0.        ,
       0.        , 0.05239625, 0.03592106, 0.08980265, 0.03829198,
       0.02913583, 0.        , 0.03335187, 0.        , 0.05415304,
       0.07184212, 0.02619813, 0.06788442, 0.        , 0.        ,
       0.02245066, 0.        , 0.03279129, 0.        , 0.02993422,
       0.05679618, 0.1000556 , 0.0554274 , 0.08122955, 0.03225806,
       0.07490059, 0.        , 0.06451613, 0.        , 0.09051256,
       0.        , 0.03456506, 0.12903226, 0.03126527, 0.        ,
       0.03592106, 0.        , 0.        , 0.        , 0.04637389,
       0.04293388, 0.07184212, 0.0277137 , 0.02707652, 0.        ,
       0.03035884, 0.02913583, 0.03745029, 0.        , 0.08519428,
       0.1000556 , 0.05679618, 0.10830607, 0.02707652, 0.        ,
       0.        , 0.04233338, 0.04233338, 0.        , 0.07074999,
       0.        , 0.07184212, 0.09677419, 0.09107651, 0.0352235 ,
       0.        , 0.        , 0.0547791 , 0.06670373, 0.1853695 ,
       0.04716666, 0.        , 0.03335187, 0.03628575, 0.        ,
       0.1796053 , 0.05827165, 0.06558258, 0.        , 0.03745029,
       0.05029955, 0.        , 0.05184758, 0.08466675, 0.03080206,
       0.02648136, 0.03456506, 0.        , 0.        , 0.        ,
       0.0237893 , 0.05415304, 0.13340747, 0.04120428, 0.02952693,
       0.02444119, 0.        , 0.08519428, 0.08466675, 0.05986843,
       0.        , 0.        , 0.        , 0.05827165, 0.        ,
       0.0277137 , 0.        , 0.0720023 , 0.11654331, 0.        ,
       0.        , 0.05679618, 0.        , 0.        , 0.        ,
       0.10182663, 0.        , 0.        , 0.07332356, 0.03126527,
       0.06253054, 0.        , 0.06160411, 0.        , 0.        ,
       0.10955821, 0.08032193, 0.        , 0.        , 0.        ,
       0.        , 0.05080005, 0.03592106, 0.        , 0.03035884,
       0.10567049, 0.02952693, 0.03829198, 0.        , 0.04981355,
       0.03456506, 0.        , 0.        , 0.03666178, 0.02839809,
       0.        , 0.        , 0.01959655, 0.        , 0.08740748,
       0.03919309, 0.        , 0.03335187, 0.03335187, 0.04233338,
       0.02707652, 0.        , 0.03745029, 0.03335187, 0.05679618,
       0.        , 0.03456506, 0.        , 0.05415304, 0.07184212,
       0.14368424, 0.        , 0.06788442, 0.05905386, 0.05905386,
       0.05986843, 0.03080206, 0.03279129, 0.07490059, 0.05609927,
       0.0513158 , 0.06071767, 0.06440082, 0.        , 0.03335187,
       0.07184212, 0.0769737 , 0.        , 0.0277137 , 0.17611749,
       0.        , 0.06253054, 0.02262814, 0.03175003, 0.02619813,
       0.02619813, 0.06956083, 0.04637389, 0.        , 0.04356068,
       0.0352235 , 0.        , 0.08414891, 0.        , 0.06842969,
       0.02540003, 0.06350006, 0.        , 0.        , 0.        ,
       0.07777138, 0.0554274 , 0.04637389, 0.        , 0.02540003,
       0.02444119, 0.02875987, 0.        , 0.05239625, 0.        ,
       0.0277137 , 0.02540003, 0.04016097, 0.        , 0.03175003,
       0.        , 0.        , 0.06558258, 0.06582684, 0.03574279,
       0.070447  , 0.        , 0.09600307, 0.0256579 , 0.03335187,
       0.0952501 , 0.06486581, 0.        , 0.02738955, 0.07944407,
       0.11235088, 0.07620008, 0.03279129, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.02514977, 0.03919309,
       0.02707652, 0.07184212, 0.        , 0.        , 0.03080206,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.02648136, 0.        , 0.05986843, 0.        ,
       0.        , 0.0229961 , 0.08240856, 0.0277137 , 0.        ,
       0.03592106, 0.06350006, 0.        , 0.0277137 , 0.03394221,
       0.        , 0.        , 0.        , 0.02993422, 0.02677398,
       0.        , 0.        , 0.        , 0.        , 0.0769737 ,
       0.02875987, 0.        , 0.15677236, 0.12143535, 0.0952501 ,
       0.        , 0.03080206, 0.06253054, 0.        , 0.03592106,
       0.08216866, 0.04843595, 0.08519428, 0.        , 0.02592379,
       0.        , 0.        , 0.04356068, 0.0513158 , 0.        ,
       0.        , 0.        , 0.0547791 , 0.02245066, 0.07572824,
       0.        , 0.10369517, 0.03745029, 0.03035884, 0.        ,
       0.        , 0.02804964, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.03175003, 0.        , 0.03080206,
       0.        , 0.0831411 , 0.        , 0.02875987, 0.        ,
       0.06253054, 0.06440082, 0.0222773 , 0.        , 0.03335187,
       0.07658396, 0.        , 0.04981355, 0.        , 0.        ,
       0.        , 0.02875987, 0.03335187, 0.05827165, 0.04637389,
       0.02262814, 0.        , 0.        , 0.        , 0.03424939,
       0.0277137 , 0.        , 0.070447  , 0.05986843, 0.09837388,
       0.1204829 , 0.        , 0.        , 0.        , 0.05827165,
       0.        , 0.        , 0.0952501 , 0.04490133, 0.03225806,
       0.10830607, 0.05827165, 0.06670373, 0.070447  , 0.10830607,
       0.0256579 , 0.05029955, 0.02162194, 0.07490059, 0.08122955,
       0.04757861, 0.07332356, 0.02087869, 0.05239625, 0.        ,
       0.03279129, 0.04233338, 0.05751973, 0.05827165, 0.03829198,
       0.08032193, 0.06253054, 0.05986843, 0.        , 0.02913583,
       0.14379933, 0.        , 0.08740748, 0.        , 0.08240856,
       0.        , 0.        , 0.        , 0.04888237, 0.13576885,
       0.05029955, 0.        , 0.04067259, 0.        , 0.0459922 ,
       0.        , 0.06913011, 0.04016097, 0.04981355, 0.03225806,
       0.        , 0.        , 0.02804964, 0.04233338, 0.        ,
       0.05080005, 0.08712137, 0.03175003, 0.0831411 , 0.03335187,
       0.07658396, 0.03919309, 0.03745029, 0.        , 0.        ,
       0.        , 0.0352235 , 0.16395646, 0.03919309, 0.        ,
       0.02046792, 0.        , 0.        , 0.07944407, 0.        ,
       0.02677398, 0.        , 0.06071767, 0.02116669, 0.04676524,
       0.03745029, 0.04120428, 0.04637389, 0.03666178, 0.03279129,
       0.02421797, 0.        , 0.03175003, 0.02677398, 0.02490677,
       0.02619813, 0.        , 0.03279129, 0.04490133, 0.06735199,
       0.06558258, 0.070447  , 0.05239625, 0.11503946, 0.        ,
       0.08414891, 0.        , 0.04934137, 0.        , 0.08240856,
       0.        , 0.        , 0.        , 0.        , 0.03279129,
       0.02421797, 0.        , 0.03666178, 0.        , 0.02875987,
       0.02421797, 0.        , 0.06253054, 0.        , 0.02993422,
       0.        , 0.0237893 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.0996271 , 0.03080206, 0.        ,
       0.        , 0.07490059, 0.02952693, 0.        , 0.        ,
       0.06670373, 0.02318694, 0.06350006, 0.        , 0.070447  ,
       0.        , 0.07658396, 0.        , 0.        , 0.        ,
       0.        , 0.04016097, 0.        , 0.05184758, 0.0513158 ,
       0.        , 0.        , 0.08980265, 0.03279129, 0.03745029,
       0.        , 0.03394221, 0.08648775, 0.        , 0.        ,
       0.0725715 , 0.        , 0.06788442, 0.02913583, 0.        ,
       0.03666178, 0.        , 0.        , 0.04637389, 0.03919309,
       0.0547791 , 0.10182663, 0.        , 0.0352235 , 0.03335187,
       0.14400461, 0.0769737 , 0.05415304, 0.03919309, 0.03745029,
       0.03035884, 0.        , 0.08519428, 0.09868274, 0.06670373,
       0.02913583, 0.0256579 , 0.02444119, 0.05296271, 0.03829198,
       0.0513158 , 0.03279129, 0.        , 0.04800154, 0.02592379,
       0.04356068, 0.03279129, 0.03829198, 0.        , 0.03394221,
       0.03394221, 0.02839809, 0.02738955, 0.        , 0.        ,
       0.10567049, 0.02952693, 0.04233338, 0.08466675, 0.        ,
       0.0862796 , 0.06913011, 0.03666178, 0.04356068, 0.        ,
       0.        , 0.03225806, 0.        , 0.04716666, 0.07838618,
       0.        , 0.03175003, 0.01415488, 0.03394221, 0.        ,

In [54]:
int(new_df[new_df['title']=='Batman Begins'].index[0])

119

In [55]:
sorted(list(enumerate(similarity[3])),reverse=True,key=lambda x:x[1])[1:8]

[(65, np.float64(0.42391137599839745)),
 (119, np.float64(0.3609974361905778)),
 (1361, np.float64(0.34668762264076824)),
 (428, np.float64(0.3333333333333334)),
 (1360, np.float64(0.32274861218395146)),
 (299, np.float64(0.3167517560464988)),
 (210, np.float64(0.27277236279499056))]

In [56]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances= similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [57]:
recommend('Batman')

Batman
Batman & Robin
The Dark Knight Rises
Batman Begins
Batman Returns

In [58]:
import pickle

In [59]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [60]:
print(new_df.columns)

Index(['id', 'title', 'Tag'], dtype='object')

In [61]:
 new_df.iloc[0].id

np.int64(19995)

In [62]:
 new_df.iloc[0]

id                                                   19995
title                                               Avatar
Tag      action adventur fantasi sciencefict culturecla...
Name: 0, dtype: object

In [72]:
new_df[new_df['title']=='Batman Begins'].id

119    272
Name: id, dtype: int64

In [67]:
new_df[['title']=='Avatar'].index[0]

KeyError: False